version: '3.7'
# Removed subprocess.CalledProcessError: Command '['/usr/local/bin/docker-credential-desktop', 'get']' returned non-zero exit status 1
# I had this:
# cat ~/.docker/config.json
# {"auths":{},"credsStore":"", "credsStore":"desktop","stackOrchestrator":"swarm"}
# I updated to this:
# {"auths":{},"credsStore":"","stackOrchestrator":"swarm"}  
services:
  hello-world-team:
    #image: in28min/todo-web-application-mysql:0.0.1-SNAPSHOT
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    
    restart: always
    networks:
      - hello-world-team-network

networks:
  hello-world-team-network: